import "./globals.css";
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import { Providers } from "./provider";

const inter = Inter({ subsets: ["latin"] });
import { AiOutlineHome } from "react-icons/ai";
import Navbar from "@/components/Navbar";
import SideBar from "@/components/SideBar";
import NavBar2 from "@/components/NavBar2";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-y-hidden">
        <Providers>
          <div className="w-screen h-screen">
            <div className="h-full  mx-auto w-full flex flex-row  bg-[#101418]">
           <div className="hidden lg:block">
           <SideBar/>
           </div>
             
              {/* <!-- Main Content --> */}
              <div className="w-full bg-[#101418] ">
                <NavBar2/>
                <div className="overflow-auto h-screen">
                {children}

                </div>
                </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
